/* Focused Daily Wird DOM/contract QA. Media is a test double; no live-backend claims. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),postcss=require('postcss');
const {boot,tick,quran,root}=require('./dom-harness.cjs');
const {verify,classify,compareProvider}=require('./quran-integrity.cjs');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'wird-reader/quran-foundation-doc-example.json'),'utf8'));
const original=new Map(quran.data.surahs.flatMap(s=>s.ayahs.map(a=>[`${s.number}:${a.numberInSurah}`,a.text])));
const results=[],apps=[],delayed=[];let count=0;
const test=async(name,fn)=>{try{await fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.stack});console.error('FAIL',name,e.message.slice(0,450));}};
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const json=data=>new Response(JSON.stringify(data),{status:200});
async function app(mode='success',settings={}){
 const a=await boot({hash:'#wird',storage:{wird_daily_hizb_v2:'1',...settings},before(w){w.HTMLMediaElement.prototype.load=function(){};},fetcher(url){
  if(!url.includes('/quran/verses/uthmani_tajweed'))return null;
  count++;
  if(mode==='failure')return new Response('{}',{status:403});
  const ch=Number(new URL(url).searchParams.get('chapter_number'));
  const verses=quran.data.surahs[ch-1].ayahs.map((a,i)=>({verse_key:`${ch}:${i+1}`,text_uthmani_tajweed:escape(a.text)}));
  if(mode==='chapter-slices'&&ch!==1&&ch!==9){const text=quran.data.surahs[ch-1].ayahs[0].text,words=quran.data.surahs[0].ayahs[0].text.replace(/^\uFEFF/,'').split(' ').length;const prefix=text.split(' ').slice(0,words).join(' ')+' ';verses[0].text_uthmani_tajweed=escape(text.slice(prefix.length));} 
  if(ch===1){
   verses[0]={...fixture.response.verses[0]};
   if(mode==='xss')verses[0].text_uthmani_tajweed+='<img src=x onerror="alert(1)"><script>alert(1)</script>';
   if(mode==='unknown')verses[0].text_uthmani_tajweed=verses[0].text_uthmani_tajweed.replace('ham_wasl','unverified_rule');
   if(mode==='mismatch')verses[0].text_uthmani_tajweed='X'+verses[0].text_uthmani_tajweed;
   if(mode==='wrong-marker')verses[0].text_uthmani_tajweed=verses[0].text_uthmani_tajweed.replace('<span class=end>١</span>','<span class=end>2</span>');
   if(mode==='duplicate')verses[1].verse_key='1:1';
   if(mode==='missing')verses.pop();
  }
  if(mode==='chapter-slices')verses.reverse();
  if(mode==='delayed')return new Promise(resolve=>delayed.push(()=>resolve(json({verses}))));
  return json({verses});
 }});
 await tick(450);apps.push(a);return a;
}
const snapshot=d=>[...d.querySelectorAll('#v22ReaderContent [data-verse-key]')].map(e=>({key:e.dataset.verseKey,text:e.querySelector('[data-ar]').textContent}));
const sameSource=d=>{for(const v of snapshot(d))assert.equal(v.text,original.get(v.key),v.key);};
(async()=>{
 const a=await app(),w=a.w,d=w.document;
 await test('Pinned complete Quran: 114 surahs / 6236 unique ordered nonempty verses',()=>{const r=verify(quran);assert.equal(r.uniqueVerseKeys,6236);assert.equal(r.duplicates,0);assert.equal(r.missing,0);});
 await test('One visible reader, inline verse containers, source text retained',()=>{assert.equal(d.querySelectorAll('#v22ReaderWorkspace').length,1);assert.equal(d.querySelectorAll('#v22ReaderContent article.v22Verse').length,0);assert(snapshot(d).length>0);assert([...d.querySelectorAll('[data-verse-key]')].every(e=>e.tagName==='SPAN'));assert(d.getElementById('wirdContent').hidden);assert.equal(d.getElementById('wirdContent').textContent,'');sameSource(d);});
 await test('Fatiha and Al-Baqarah boundary: headings and basmalah exactly as supplied',()=>{assert.deepEqual([...d.querySelectorAll('.wird-surah')].map(e=>e.dataset.surahNumber),['1','2']);assert.equal(d.querySelectorAll('.wird-ayah-marker').length,snapshot(d).length);assert.equal(d.querySelectorAll('.v22Bismillah,.v22InlineBismillah').length,0);const opening=d.querySelector('[data-verse-key="2:1"] .wird-basmala');assert(opening);assert.equal(opening.textContent,original.get('1:1').replace(/^\uFEFF/,'')+' ');assert.equal(d.querySelectorAll('[data-verse-key="1:1"] .wird-basmala').length,0);sameSource(d);});
 await test('Tajweed legend is collapsed, accessible and has exactly eight semantic colors',()=>{const b=d.querySelector('[data-legend]'),p=d.getElementById('v22TajweedLegend');assert(p.hidden);b.click();assert(!p.hidden);assert.equal(b.getAttribute('aria-expanded'),'true');assert.equal(p.querySelectorAll('.v22LegendItem').length,8);assert(p.querySelector('[data-tajweed-rule="tafkhim"]'));b.click();assert(p.hidden);});
 await test('Official Quran Foundation sample annotation: retain every original code point',async()=>{d.querySelector('[data-toggle="tajweed"]').click();await tick(100);const e=d.querySelector('[data-verse-key="1:1"] [data-ar]');assert(e.querySelector('tajweed'));assert.equal(e.textContent,original.get('1:1'));assert.deepEqual([...new Set([...e.querySelectorAll('tajweed')].map(t=>t.className))].sort(),['ham_wasl','laam_shamsiyah','madda_normal','madda_permissible'].sort());assert.equal(e.querySelectorAll('span.end').length,0);sameSource(d);});
 await test('Tajweed switch does not change position, ordering, text or number of markers',async()=>{const before=snapshot(d),pos=w.eval('currentPortion'),audio=d.querySelector('.wird-audio-controls');d.querySelector('[data-toggle="tajweed"]').click();await tick(30);assert.equal(d.querySelectorAll('#v22ReaderContent tajweed').length,0);assert.deepEqual(snapshot(d),before);assert.equal(w.eval('currentPortion'),pos);assert.equal(d.querySelector('.wird-audio-controls'),audio);d.querySelector('[data-toggle="tajweed"]').click();await tick(30);assert.deepEqual(snapshot(d),before);assert.equal(d.querySelector('[data-toggle="tajweed"]').getAttribute('aria-pressed'),'true');});
 await test('Selected verse uses unchanged audio engine; second click stops it',async()=>{d.querySelector('[data-select-verse="1:2"]').click();await tick(20);assert.equal(w.eval('activeAyahAudio.id'),'1_2');assert(w.eval('ayahAudioPlayer.src').includes('/001002.mp3'));assert(d.querySelector('#audioBtn_1_2').classList.contains('playing'));assert.equal(d.querySelector('[data-verse-key="1:2"] .wird-ayah-marker').textContent,'٢');d.querySelector('[data-select-verse="1:2"]').click();await tick(20);assert.equal(w.eval('activeAyahAudio'),null);});
 await test('Changing Tajweed and translation preserves the active audio control',async()=>{d.querySelector('[data-select-verse="1:3"]').click();await tick(10);const audio=d.getElementById('audioBtn_1_3');d.querySelector('[data-toggle="tajweed"]').click();await tick(10);assert.equal(w.eval('activeAyahAudio.id'),'1_3');assert.equal(d.getElementById('audioBtn_1_3'),audio);const t=d.querySelector('[data-reader-translation]');t.checked=true;t.dispatchEvent(new w.Event('change',{bubbles:true}));await tick(20);assert.equal(d.getElementById('audioBtn_1_3'),audio);assert.equal(d.querySelectorAll('.v22TranslationLine').length,snapshot(d).length);sameSource(d);});
 await test('Reciter selection persists and stops the previous recitation',async()=>{const s=d.getElementById('v22AyahReciter');s.value='alafasy_murattal';s.dispatchEvent(new w.Event('change',{bubbles:true}));await tick(10);assert.equal(w.getSelectedAyahReciter(),'alafasy_murattal');assert.equal(w.eval('activeAyahAudio'),null);d.querySelector('[data-select-verse="1:4"]').click();await tick(10);assert(w.eval('ayahAudioPlayer.src').includes('/Alafasy_128kbps/001004.mp3'));});
 await test('Next/previous portion stops previous audio and restores the correct source range',async()=>{const prev=snapshot(d);d.querySelector('[data-portion="1"]').click();await tick(30);assert.equal(w.eval('currentPortion'),2);assert.equal(w.eval('activeAyahAudio'),null);assert.notDeepEqual(snapshot(d),prev);sameSource(d);d.querySelector('[data-portion="-1"]').click();await tick(30);assert.deepEqual(snapshot(d),prev);});
 await test('Completion and one/two-hizb controls retain progress contracts',async()=>{d.querySelector('[data-reader-complete]').click();await tick(40);const done=w.getDoneMap();assert.equal(Object.values(done).filter(Boolean).length,1);assert(Number(d.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'))>0);const amount=d.getElementById('v22DailyAmount');amount.value='2';amount.dispatchEvent(new w.Event('change',{bubbles:true}));await tick(40);assert.equal(w.eval('dailyHizb'),2);assert.equal(w.eval('portions.length'),30);assert.equal(w.localStorage.getItem('wird_daily_hizb_v2'),'2');sameSource(d);const currentAmount=d.getElementById('v22DailyAmount');currentAmount.value='1';currentAmount.dispatchEvent(new w.Event('change',{bubbles:true}));await tick(40);assert.equal(w.eval('portions.length'),60);});
 await test('Every one-hizb portion renders each of the 6236 ayahs exactly once',async()=>{if(d.querySelector('[data-reader-translation]').checked){d.querySelector('[data-reader-translation]').click();await tick(20);}const all=[],openings=[];for(let p=1;p<=60;p++){w.eval(`currentPortion=${p};renderPortion(currentPortion)`);sameSource(d);const vs=snapshot(d);all.push(...vs.map(v=>v.key));openings.push(...[...d.querySelectorAll('.wird-basmala')].map(e=>e.closest('[data-verse-key]').dataset.verseKey));assert.equal(new Set(vs.map(v=>v.key)).size,vs.length);}assert.deepEqual(all,[...original.keys()]);assert.equal(new Set(all).size,6236);assert.equal(openings.length,112);assert.equal(new Set(openings).size,112);assert(!openings.includes('1:1')&&!openings.includes('9:1'));});
 await test('Ali Imran 102–107, long ayah 2:282, and Tawbah boundary have valid source flow',async()=>{for(const k of ['3:102','3:103','3:104','3:105','3:106','3:107','2:282','9:1']){const p=w.eval(`portions.findIndex(p=>p.some(a=>a.surahNumber+':'+a.numberInSurah==='${k}'))+1`);w.eval(`currentPortion=${p};renderPortion(currentPortion)`);sameSource(d);assert(d.querySelector(`[data-verse-key="${k}"]`));}const tawbah=d.querySelector('.wird-surah[data-surah-number="9"]');assert(tawbah);assert.equal(tawbah.querySelector('[data-ar]').textContent,original.get('9:1'));assert(!tawbah.querySelector('.v22Bismillah'));});
 await test('Reader-only translation keys are complete in all seven languages',async()=>{const keys=Object.keys(JSON.parse(fs.readFileSync(path.join(__dirname,'wird-reader/translation-keys.json'),'utf8')));for(const code of ['ar','en','fr','id','tr','ur','es']){w.ZadI18n.setLocale(code);w.v22OnLanguageChange();await tick(10);for(const k of keys)assert(w.ZadI18nCatalog[k][code]);assert.equal(d.querySelectorAll('.v22LegendItem').length,8);sameSource(d);}assert.equal(w.ZadI18n.missing.size,0);w.ZadI18n.setLocale('ar');});
 for(const mode of ['failure','duplicate','mismatch','wrong-marker','unknown'])await test(`Plain-text fallback for ${mode} data; no invented Tajweed`,async()=>{const e=await app(mode,{zad_reader_tajweed_v1:'true'});const doc=e.w.document;sameSource(doc);assert.equal(doc.querySelector('[data-verse-key="1:1"] [data-ar]').querySelectorAll('tajweed').length,0);assert(!doc.getElementById('wirdTajweedStatus').hidden);});
 await test('A missing ayah does not discard valid annotations for another ayah in its chapter',async()=>{const e=await app('missing',{zad_reader_tajweed_v1:'true'}),doc=e.w.document;sameSource(doc);assert(doc.querySelector('[data-verse-key="1:1"] tajweed'));assert.equal(doc.querySelector('[data-verse-key="1:7"] tajweed'),null);assert(!doc.getElementById('wirdTajweedStatus').hidden);});
 await test('Trusted-markup sanitizer strips active content before annotation',async()=>{const e=await app('xss',{zad_reader_tajweed_v1:'true'});const el=e.w.document.querySelector('[data-verse-key="1:1"] [data-ar]');assert(el.querySelector('tajweed'));assert.equal(el.querySelectorAll('script,img,[onclick],[style],svg').length,0);sameSource(e.w.document);});
 await test('Existing integrity comparator detects all keys and substantive changes in a synthetic control',()=>{const control={verses:[...original].map(([verse_key,text_uthmani])=>({verse_key,text_uthmani}))};assert.equal(compareProvider(quran,control).EXACT_MATCH,6236);control.verses[0].text_uthmani+='X';assert.equal(compareProvider(quran,control).SUBSTANTIVE_DIFFERENCE,1);control.verses[1].verse_key='1:1';assert.throws(()=>compareProvider(quran,control),/ordering/);});
 await test('All new CSS is scoped to Daily Wird; Tajweed has inherited inline geometry',()=>{const css=fs.readFileSync(path.join(root,'assets/css/reader.css'),'utf8');const patch=css.slice(css.indexOf('/* Daily Wird only.'));const tree=postcss.parse(patch);tree.walkRules(r=>{assert(r.selectors.every(s=>s.includes('#wirdModule')),r.selector);if(r.selector.includes('tajweed')&&!r.selector.includes('data-tajweed-rule')){const d=Object.fromEntries(r.nodes.filter(n=>n.type==='decl').map(n=>[n.prop,n.value]));assert.equal(d.display,'inline');assert.equal(d.font,'inherit');assert.equal(d['line-height'],'inherit');assert.equal(d.position,'static');assert.equal(d.transform,'none');}});assert(!patch.includes('text-align: justify'));});
 await test('360/390/430/768/1440 layout contracts in both modes (not rendered browser QA)',async()=>{for(const theme of ['light','dark'])for(const width of [360,390,430,768,1440]){Object.defineProperty(w,'innerWidth',{value:width,configurable:true});d.documentElement.dataset.theme=theme;w.eval('currentPortion=1;renderPortion(currentPortion)');sameSource(d);assert.equal(d.querySelectorAll('#v22ReaderWorkspace').length,1);const style=w.getComputedStyle(d.querySelector('.wird-mushaf-text'));assert.equal(style.direction,'rtl');assert.equal(style.display,'block');assert.equal(w.getComputedStyle(d.querySelector('[data-verse-key="1:1"]')).display,'block');assert.equal(w.getComputedStyle(d.querySelector('[data-verse-key="2:1"]')).display,'inline');}});
 await test('Light/dark Tajweed colors have >=4.5 contrast on all existing reader surfaces',()=>{const colors=JSON.parse(fs.readFileSync(path.join(__dirname,'wird-reader/tajweed-colors.json'),'utf8'));const pal=JSON.parse(fs.readFileSync(path.join(root,'data/accent-palettes.json'),'utf8'));const lum=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4).reduce((s,c,i)=>s+c*[.2126,.7152,.0722][i],0);for(const theme of ['light','dark'])for(const color of Object.values(colors.actualReaderColors[theme]))for(const p of Object.values(pal))for(const bg of ['--color-surface','--color-surface-alt']){const a=lum(color),b=lum(p[theme][bg]);assert((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5);}});
 await test('Bundled-font ink envelope fits the chosen line height',()=>{const m=JSON.parse(fs.readFileSync(path.join(__dirname,'wird-reader/font-metrics.json'),'utf8'));assert(m.safeVerticalMetric);assert(m.maximumAdjacentLineInkEnvelopePx<m.lineBoxAt48Px);assert(m.maximumAdjacentLineInkEnvelopePx>m.previousMobileLineBoxAt48Px);const css=fs.readFileSync(path.join(root,'assets/css/reader.css'),'utf8');assert(css.includes('line-height: 2.9'));});
 await test('Refresh restores reciter, completion and Tajweed preference',async()=>{if(d.querySelector('[data-toggle="tajweed"]').getAttribute('aria-pressed')!=='true')d.querySelector('[data-toggle="tajweed"]').click();await tick(30);const storage=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));const r=await app('success',storage);assert.equal(r.w.getSelectedAyahReciter(),'alafasy_murattal');assert.equal(Object.values(r.w.getDoneMap()).filter(Boolean).length,1);assert.equal(r.w.document.querySelector('[data-toggle="tajweed"]').getAttribute('aria-pressed'),'true');sameSource(r.w.document);});
 await test('Separate opening lines and bundled-font selection at 2:1 and 3:1 without text mutation',async()=>{
  for(const k of ['2:1','3:1']){const p=w.eval(`portions.findIndex(p=>p.some(a=>a.surahNumber+':'+a.numberInSurah==='${k}'))+1`);w.eval(`currentPortion=${p};renderPortion(currentPortion)`);const e=d.querySelector(`[data-verse-key="${k}"]`);assert.equal(e.querySelectorAll('.wird-basmala').length,1);assert.equal(e.querySelector('.wird-verse-text').dataset.quranFont,'opening');assert.equal(e.querySelector('.wird-basmala').textContent+e.querySelector('.wird-verse-text').textContent,original.get(k));assert(w.getComputedStyle(e.querySelector('.wird-verse-text')).fontFamily.includes('Zad Sans'));assert.equal(w.getComputedStyle(d.querySelector('.wird-mushaf-text')).letterSpacing,'0');sameSource(d);}
 });
 await test('Verse-key alignment accepts shuffled provider-shaped chapter responses without their unnumbered basmalah',async()=>{
  // Plain payloads test transport/alignment only; no invented Tajweed annotations.
  const e=await app('chapter-slices',{zad_reader_tajweed_v1:'true'}),doc=e.w.document;
  for(const k of ['1:1','2:1','3:1','36:1','112:1','9:1']){const p=e.w.eval(`portions.findIndex(p=>p.some(a=>a.surahNumber+':'+a.numberInSurah==='${k}'))+1`);e.w.eval(`currentPortion=${p};renderPortion(currentPortion)`);await tick(80);sameSource(doc);assert(doc.querySelector(`[data-verse-key="${k}"] [data-ar]`).textContent);assert(doc.getElementById('wirdTajweedStatus').hidden,k);if(k==='9:1')assert.equal(doc.querySelector(`[data-verse-key="${k}"] .wird-basmala`),null);}
 });
 await test('NFC-equivalent annotations preserve original codepoints; meaningful differences stay plain',()=>{
  // Exercise the exact production parser with non-Quran strings for Unicode edge cases.
  const parser=require('@babel/parser'),src=fs.readFileSync(path.join(root,'assets/js/quran-reader.js'),'utf8');const body=parser.parse(src).program.body[0].expression.callee.body.body;
  const names=new Set(['canonicalUnits','alignAnnotations']);const declarations=body.filter(n=>n.type==='FunctionDeclaration'&&names.has(n.id.name)).map(n=>src.slice(n.start,n.end)).join('\n');
  w.eval(`window.__unicodeProbe=(function(){${declarations};return {alignAnnotations};})();`);
  const f=w.__unicodeProbe.alignAnnotations;assert.deepEqual([...f('A\u0301',[{char:'Á',annotation:'madda_normal'}])],['madda_normal','madda_normal']);assert.equal(f('A\u0301',[{char:'A',annotation:'madda_normal'}]),null);assert.equal(f('A',[{char:'B',annotation:'madda_normal'}]),null);delete w.__unicodeProbe;
 });
 await test('Late chapter responses cannot re-enable Tajweed or replace a different current portion',async()=>{
  const e=await app('delayed',{zad_reader_tajweed_v1:'true'}),doc=e.w.document;doc.querySelector('[data-portion="1"]').click();await tick(20);doc.querySelector('[data-toggle="tajweed"]').click();const before=snapshot(doc);for(const resolve of delayed.splice(0))resolve();await tick(80);assert.deepEqual(snapshot(doc),before);assert.equal(doc.querySelectorAll('#v22ReaderContent tajweed').length,0);assert.equal(doc.querySelector('[data-toggle="tajweed"]').getAttribute('aria-pressed'),'false');sameSource(doc);
 });
 await test('No reader console errors in focused runs',()=>{for(const app of apps)assert.deepEqual(app.errors,[]);});
 const report={generated:new Date().toISOString(),scope:'Daily Wird only',testType:'DOM contracts with test media and cached documentation example; NOT live Quran.com corpus / browser rendering / live audio.',passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,results};
 fs.writeFileSync(path.join(__dirname,'wird-reader-results.json'),JSON.stringify(report,null,2)+'\n');
 console.log(JSON.stringify({passed:report.passed,failed:report.failed}));process.exit(report.failed?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
