import { createClient } from 'npm:@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, apikey, authorization','Access-Control-Allow-Methods':'POST, OPTIONS'}
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}
function safeName(name:string){const ext=(name.split('.').pop()||'mp4').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,6)||'mp4';return `video.${ext}`}
function adminKey(){const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(legacy)return legacy;try{const x=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');return x.default||''}catch(_){return ''}}
function clientIp(req:Request){let raw=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'').split(',')[0].trim();if(raw.startsWith('::ffff:'))raw=raw.slice(7);return raw||'unknown'}
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405)
 try{
  const body=await req.json().catch(()=>({}));const title=String(body?.title||'').trim().slice(0,140);const original=String(body?.file_name||'').trim().slice(0,180);const mime=String(body?.mime_type||'').toLowerCase();const size=Number(body?.file_size||0)
  if(!title||title.length<2)return json({error:'title_required',message:'اكتب عنوانًا واضحًا للمقطع.'},400);if(!original)return json({error:'file_required',message:'اختر ملف الفيديو أولًا.'},400);if(!['video/mp4','video/webm','video/quicktime','video/x-m4v'].includes(mime))return json({error:'unsupported_video_type',message:'صيغة الفيديو غير مدعومة.'},400);if(!Number.isFinite(size)||size<=0||size>50*1024*1024)return json({error:'file_too_large',max_mb:50,message:'حجم الفيديو أكبر من الحد المسموح.'},400)
  const url=Deno.env.get('SUPABASE_URL')||'';const key=adminKey();if(!url||!key)return json({error:'server_config_error',message:'إعدادات خادم الرفع غير مكتملة.'},500);const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})
  const ipRaw=clientIp(req);const ipHex=ipRaw==='unknown'?null:await sha(ipRaw)
  if(ipHex){const b=await sb.from('zad_ip_bans').select('ip_hash').eq('ip_hash',ipHex).eq('is_active',true).maybeSingle();if(b.error)throw b.error;if(b.data)return json({error:'ip_banned',message:'تم حظر هذا الاتصال من زاد الإسلام.'},403)}
  let submitterUserId:string|null=null;let submitterName:string|null=null;const auth=req.headers.get('authorization')||'';const token=auth.toLowerCase().startsWith('bearer ')?auth.slice(7).trim():''
  if(token){try{const u=await sb.auth.getUser(token);if(!u.error&&u.data?.user){submitterUserId=u.data.user.id;const pr=await sb.from('profiles').select('username,display_name,account_status').eq('id',submitterUserId).maybeSingle();if(pr.data?.account_status==='banned')return json({error:'account_banned',message:'هذا الحساب موقوف من إدارة الموقع.'},403);submitterName=String(pr.data?.username||pr.data?.display_name||u.data.user.user_metadata?.username||u.data.user.user_metadata?.display_name||'').trim().slice(0,80)||null;if(ipHex){const l=await sb.from('zad_user_ip_links').upsert({user_id:submitterUserId,ip_hash:ipHex,last_seen_at:new Date().toISOString()},{onConflict:'user_id,ip_hash'});if(l.error)console.warn('ip_link',l.error.message)}}}catch(_){}}
  if(ipHex){const since=new Date(Date.now()-60*60*1000).toISOString();const rate=await sb.from('zad_talk_upload_attempts').select('*',{count:'exact',head:true}).eq('ip_hash',ipHex).gte('created_at',since);if(rate.error)throw rate.error;if((rate.count||0)>=8)return json({error:'rate_limited',message:'تم الوصول للحد المؤقت للرفع. حاول بعد ساعة.'},429)}
  const receipt=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');const receiptHash=await sha(receipt);const id=crypto.randomUUID();const path=`${id}/${safeName(original)}`;const expires=new Date(Date.now()+2*60*60*1000).toISOString()
  const ins=await sb.from('zad_talk_submissions').insert({id,title,submitter_name:submitterName,submitter_user_id:submitterUserId,media_kind:'video',storage_path:path,original_file_name:original,mime_type:mime,file_size:size,status:'uploading',upload_receipt_hash:receiptHash,upload_expires_at:expires});if(ins.error)throw ins.error
  if(ipHex){const attempt=await sb.from('zad_talk_upload_attempts').insert({ip_hash:ipHex,submission_id:id});if(attempt.error){await sb.from('zad_talk_submissions').delete().eq('id',id);throw attempt.error}}
  const signed=await sb.storage.from('zad-talk-media').createSignedUploadUrl(path);if(signed.error||!signed.data){await sb.from('zad_talk_submissions').delete().eq('id',id);throw signed.error||new Error('signed_upload_failed')}
  return json({ok:true,id,path:signed.data.path||path,token:signed.data.token,receipt,expires_at:expires})
 }catch(e){console.error('zad-talk-create-upload',e);return json({error:'server_error',message:'تعذر تجهيز رفع الفيديو على الخادم. حاول مرة أخرى.'},500)}
})
